function D = buildScenarioPlotData(SCENARIO)
%BUILDSCENARIOPLOTDATA Extract real AoI/user coordinates from a generated NAPOLEON+ scenario.
%
% This helper is GUI-facing. It does not run the simulation and it does not
% invent users. It reads the actual GroundStations stored in the MATLAB
% satelliteScenario object generated by run_NAPOLEON_scenario.
%
% Output fields are plot-ready and intentionally simple.

    if nargin < 1 || isempty(SCENARIO)
        error('buildScenarioPlotData:MissingScenario', 'SCENARIO is required.');
    end

    if ~isfield(SCENARIO, 'satelliteScenario') || isempty(SCENARIO.satelliteScenario)
        error('buildScenarioPlotData:MissingSatelliteScenario', ...
            'SCENARIO.satelliteScenario is missing or empty.');
    end

    if ~isfield(SCENARIO, 'configAoI') || isempty(SCENARIO.configAoI)
        error('buildScenarioPlotData:MissingAoI', ...
            'SCENARIO.configAoI is missing or empty.');
    end

    sc = SCENARIO.satelliteScenario;
    aoi = SCENARIO.configAoI;

    %% Extract real ground-station/user positions
    gs = sc.GroundStations;

    if isempty(gs)
        userLat = [];
        userLon = [];
        userAlt = [];
        userNames = strings(0,1);
    else
        userLat = readNumericObjectArrayProperty(gs, 'Latitude');
        userLon = readNumericObjectArrayProperty(gs, 'Longitude');

        if objectHasProperty(gs, 'Altitude')
            userAlt = readNumericObjectArrayProperty(gs, 'Altitude');
        else
            userAlt = zeros(size(userLat));
        end

        if objectHasProperty(gs, 'Name')
            userNames = readStringObjectArrayProperty(gs, 'Name');
        else
            userNames = compose('User %d', 1:numel(userLat)).';
        end
    end

    userLat = userLat(:);
    userLon = userLon(:);
    userAlt = userAlt(:);
    userNames = userNames(:);

    valid = isfinite(userLat) & isfinite(userLon);
    userLat = userLat(valid);
    userLon = userLon(valid);
    userAlt = userAlt(valid);
    userNames = userNames(valid);

    userRadius = 1.035 + normalizeAltitude(userAlt);
    [userX, userY, userZ] = geodeticToSphereXYZ(userLat, userLon, userRadius);

    %% AoI curved surface mesh
    latStep = safePositiveStep(aoi, 'deltaLat', 2);
    lonStep = safePositiveStep(aoi, 'deltaLon', 2);

    nLat = max(18, ceil(abs(aoi.latMax - aoi.latMin)/latStep)*4 + 1);
    nLon = max(18, ceil(abs(aoi.lonMax - aoi.lonMin)/lonStep)*4 + 1);

    latGrid = linspace(aoi.latMin, aoi.latMax, nLat);
    lonGrid = linspace(aoi.lonMin, aoi.lonMax, nLon);
    [lonMesh, latMesh] = meshgrid(lonGrid, latGrid);
    [meshX, meshY, meshZ] = geodeticToSphereXYZ(latMesh, lonMesh, 1.000);

    %% AoI curved boundary, sampled densely so it follows the sphere
    nEdge = 80;
    southLon = linspace(aoi.lonMin, aoi.lonMax, nEdge);
    eastLat  = linspace(aoi.latMin, aoi.latMax, nEdge);
    northLon = linspace(aoi.lonMax, aoi.lonMin, nEdge);
    westLat  = linspace(aoi.latMax, aoi.latMin, nEdge);

    boundaryLat = [aoi.latMin*ones(1,nEdge), eastLat, aoi.latMax*ones(1,nEdge), westLat];
    boundaryLon = [southLon, aoi.lonMax*ones(1,nEdge), northLon, aoi.lonMin*ones(1,nEdge)];
    [boundaryX, boundaryY, boundaryZ] = geodeticToSphereXYZ(boundaryLat, boundaryLon, 1.012);

    %% Latitude/longitude guide lines inside the AoI
    latLines = unique([aoi.latMin:latStep:aoi.latMax, aoi.latMax]);
    lonLines = unique([aoi.lonMin:lonStep:aoi.lonMax, aoi.lonMax]);

    %% View and limits focused on the AoI, not on the full globe
    allX = [meshX(:); boundaryX(:); userX(:)];
    allY = [meshY(:); boundaryY(:); userY(:)];
    allZ = [meshZ(:); boundaryZ(:); userZ(:)];

    if isempty(allX)
        limX = [-1.1 1.1];
        limY = [-1.1 1.1];
        limZ = [-1.1 1.1];
    else
        [limX, limY, limZ] = paddedLimits(allX, allY, allZ, 0.18);
    end

    centerLat = 0.5*(aoi.latMin + aoi.latMax);
    centerLon = 0.5*(aoi.lonMin + aoi.lonMax);

    %% Return data
    D = struct();
    D.numUsers = numel(userLat);
    D.userLat = userLat;
    D.userLon = userLon;
    D.userAlt = userAlt;
    D.userNames = userNames;
    D.userXYZ = [userX(:), userY(:), userZ(:)];

    D.aoi = aoi;
    D.aoiLatGrid = latGrid;
    D.aoiLonGrid = lonGrid;
    D.aoiLatMesh = latMesh;
    D.aoiLonMesh = lonMesh;
    D.aoiMeshX = meshX;
    D.aoiMeshY = meshY;
    D.aoiMeshZ = meshZ;
    D.aoiBoundaryLat = boundaryLat(:);
    D.aoiBoundaryLon = boundaryLon(:);
    D.aoiBoundaryXYZ = [boundaryX(:), boundaryY(:), boundaryZ(:)];
    D.latLines = latLines(:);
    D.lonLines = lonLines(:);

    D.centerLat = centerLat;
    D.centerLon = centerLon;
    D.viewAz = centerLon + 118;
    D.viewEl = max(18, min(62, centerLat - 10));
    D.xLim = limX;
    D.yLim = limY;
    D.zLim = limZ;

    if isfield(SCENARIO, 'params') && isfield(SCENARIO.params, 'seed')
        D.seed = SCENARIO.params.seed;
    else
        D.seed = NaN;
    end

    if isfield(SCENARIO, 'startTime')
        D.startTime = SCENARIO.startTime;
    else
        D.startTime = [];
    end

    if isfield(SCENARIO, 'stopTime')
        D.stopTime = SCENARIO.stopTime;
    else
        D.stopTime = [];
    end

    if isfield(SCENARIO, 'sampleTime')
        D.sampleTime = SCENARIO.sampleTime;
    else
        D.sampleTime = [];
    end
end

%% Local helpers
function tf = objectHasProperty(objArray, propName)
    tf = false;
    if isempty(objArray)
        return;
    end

    try
        tf = isprop(objArray(1), propName);
    catch
        try
            objArray(1).(propName); %#ok<VUNUS>
            tf = true;
        catch
            tf = false;
        end
    end
end

function values = readNumericObjectArrayProperty(objArray, propName)
    n = numel(objArray);
    values = nan(n,1);

    for i = 1:n
        try
            raw = objArray(i).(propName);
            raw = double(raw);
            if isempty(raw)
                values(i) = NaN;
            else
                values(i) = raw(1);
            end
        catch
            values(i) = NaN;
        end
    end
end

function values = readStringObjectArrayProperty(objArray, propName)
    n = numel(objArray);
    values = strings(n,1);

    for i = 1:n
        try
            raw = objArray(i).(propName);
            values(i) = string(raw);
        catch
            values(i) = "";
        end
    end
end

function extraRadius = normalizeAltitude(alt_m)
    % The GUI plot is a local 3D visualization, not a geodetic model.
    % Ground terminals normally sit at altitude 0, but if altitude exists we
    % apply a tiny normalized offset so it does not explode the sphere scale.
    if isempty(alt_m) || all(~isfinite(alt_m))
        extraRadius = zeros(size(alt_m));
        return;
    end

    alt_m = double(alt_m);
    alt_m(~isfinite(alt_m)) = 0;

    maxAbs = max(abs(alt_m));
    if maxAbs <= 0
        extraRadius = zeros(size(alt_m));
    else
        extraRadius = 0.012 * alt_m ./ maxAbs;
    end
end

function step = safePositiveStep(aoi, fieldName, fallback)
    if isfield(aoi, fieldName)
        step = double(aoi.(fieldName));
        if ~isfinite(step) || step <= 0
            step = fallback;
        end
    else
        step = fallback;
    end
end

function [x, y, z] = geodeticToSphereXYZ(latDeg, lonDeg, radius)
    if isscalar(radius)
        radius = radius .* ones(size(latDeg));
    end

    x = radius .* cosd(latDeg) .* cosd(lonDeg);
    y = radius .* cosd(latDeg) .* sind(lonDeg);
    z = radius .* sind(latDeg);
end

function [limX, limY, limZ] = paddedLimits(x, y, z, padFraction)
    limX = padded1D(x, padFraction);
    limY = padded1D(y, padFraction);
    limZ = padded1D(z, padFraction);
end

function lim = padded1D(v, padFraction)
    v = v(isfinite(v));
    if isempty(v)
        lim = [-1 1];
        return;
    end

    vmin = min(v);
    vmax = max(v);
    span = vmax - vmin;

    if span <= eps
        span = max(abs(vmax), 1) * 0.1;
    end

    pad = padFraction * span;
    lim = [vmin - pad, vmax + pad];
end
